#!/usr/bin/env node
/* eslint-disable no-console */

const readline = require('readline')
const os = require('os')
const User = require('./web/app/models/User')

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
})

rl.question('Your name: ', (name) => {
    rl.question('Your email: ', (email) => {
        rl.question('Choose password: ', (password) => {
            (async function register() {
                const {status, message} = await User.register({name, email, password})
                if (status === 500) {
                    console.warn(message)
                }
                console.log(`Hi, ${name}, please use ${email} and ${password} as your logins`)
                rl.close()
            })()
        })
    })
})


rl.on('close', () => {
    console.log(`\n Bye ${os.userInfo().username}`)
    process.exit(0)
})